-- student_trimester_reports: one AI narrative per (tenant, student, trimester, academic_year, subject_name)
-- NOTE: this table already existed in production with the schema below.
-- CREATE TABLE IF NOT EXISTS was a no-op; the column names used by the backend
-- must match this schema (report_text, generated_at) not the initial draft.
--
-- Actual production schema (for documentation):
--
-- CREATE TABLE IF NOT EXISTS student_trimester_reports (
--   id              UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
--   tenant_id       UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
--   student_id      UUID         NOT NULL REFERENCES students(id) ON DELETE CASCADE,
--   trimester       INTEGER      NOT NULL CHECK (trimester = ANY (ARRAY[1, 2, 3])),
--   academic_year   TEXT         NOT NULL,
--   subject_name    TEXT         NOT NULL,
--   report_text     TEXT         NOT NULL,
--   generated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
--   CONSTRAINT student_trimester_reports_tenant_id_student_id_trimester_ac_key
--     UNIQUE (tenant_id, student_id, trimester, academic_year, subject_name)
-- );

-- No DDL needed: table and constraints already exist in production.
SELECT 1;
